version: '3.7'

services:
  BackEnd:
   env_file:
      - "../config/server.env"
   image: 'golang:1.19.8-alpine3.17'
   container_name:  'ASTRIC-${CONAINER_NAME}-BackEnd'
   user: ${USER}
   working_dir: /app
   command: > 
     sh -c "go run main.go"
   networks:
    - default
   ports:
    - "${API_FIREWALL}:3000" #API map port
    - "${WS_FIREWALL}:8000" #WS map port
   volumes:
    - "../../:/app"

networks:
  default:
    name: ${NET}
    external: ${NET_EXTERNAL}